const pieces = { w:{k:'♔',q:'♕',r:'♖',b:'♗',n:'♘',p:'♙'}, b:{k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'} };
const names={k:'King',q:'Queen',r:'Rook',b:'Bishop',n:'Knight',p:'Pawn'};
const levels={beginner:{label:'Beginner',depth:1,random:.20,time:.15},easy:{label:'Casual',depth:2,random:.08,time:.3},medium:{label:'Balanced',depth:3,random:.03,time:.65},sharp:{label:'Sharp',depth:5,random:0,time:3},expert:{label:'Expert',depth:6,random:0,time:6}};
let state, selected=null, legal=[], difficulty='easy', thinking=false;
const boardEl=document.querySelector('#board'), moveList=document.querySelector('#moveList'), moveCount=document.querySelector('#moveCount'), turnLabel=document.querySelector('#turnLabel'), thinkingEl=document.querySelector('#thinking'), botLevelLabel=document.querySelector('#botLevelLabel'), toast=document.querySelector('#toast');
function initialBoard(){const back=['r','n','b','q','k','b','n','r']; return [back.map(p=>({c:'b',p})),...Array(6).fill(null).map((_,r)=>r===1?Array(8).fill(0).map(()=>({c:'b',p:'p'})):r===5?Array(8).fill(0).map(()=>({c:'w',p:'p'})):Array(8).fill(null)),back.map(p=>({c:'w',p}))];}
function fresh(color='w'){return {board:initialBoard(),turn:'w',playerColor:color,castle:{wK:true,wQ:true,bK:true,bQ:true},enPassant:null,last:null,moves:[],snapshots:[],over:false};}
function clone(s){return {board:s.board.map(row=>row.map(x=>x&&{...x})),turn:s.turn,castle:{...s.castle},enPassant:s.enPassant,last:s.last,moves:[...s.moves],over:s.over};}
function inside(r,c){return r>=0&&r<8&&c>=0&&c<8} function other(c){return c==='w'?'b':'w'}
function attacked(s,r,c,by){for(let rr=0;rr<8;rr++)for(let cc=0;cc<8;cc++){const x=s.board[rr][cc];if(!x||x.c!==by)continue;const dr=r-rr,dc=c-cc,ad=Math.abs(dr),ac=Math.abs(dc);if(x.p==='p'&&dr===(by==='w'?-1:1)&&ac===1)return true;if(x.p==='n'&&((ad===2&&ac===1)||(ad===1&&ac===2)))return true;if((x.p==='k'&&ad<=1&&ac<=1)||(x.p==='r'&&(dr===0||dc===0))||(x.p==='b'&&ad===ac)||(x.p==='q'&&(dr===0||dc===0||ad===ac))){let sr=Math.sign(dr),sc=Math.sign(dc),a=rr+sr,b=cc+sc,clear=true;while(a!==r||b!==c){if(s.board[a][b]){clear=false;break}a+=sr;b+=sc}if(clear)return true}}return false}
function inCheck(s,color){for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(s.board[r][c]?.c===color&&s.board[r][c].p==='k')return attacked(s,r,c,other(color));return true}
function pseudo(s,r,c){const x=s.board[r][c], out=[];if(!x)return out;const add=(rr,cc,extra={})=>{if(!inside(rr,cc)||s.board[rr][cc]?.c===x.c)return false;out.push({fr:r,fc:c,tr:rr,tc:cc,...extra});return !s.board[rr][cc]};
 if(x.p==='p'){let d=x.c==='w'?-1:1,start=x.c==='w'?6:1;if(inside(r+d,c)&&!s.board[r+d][c]){add(r+d,c);if(r===start&&!s.board[r+2*d][c])add(r+2*d,c)}for(const dc of [-1,1])if(inside(r+d,c+dc)&&(s.board[r+d][c+dc]?.c===other(x.c)||s.enPassant===`${r+d},${c+dc}`))add(r+d,c+dc,s.enPassant===`${r+d},${c+dc}`?{ep:true}:{});}else if(x.p==='n'){for(const [dr,dc] of [[2,1],[2,-1],[-2,1],[-2,-1],[1,2],[1,-2],[-1,2],[-1,-2]])add(r+dr,c+dc)}else if(x.p==='k'){for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(dr||dc)add(r+dr,c+dc);const row=x.c==='w'?7:0;if(r===row&&c===4&&!inCheck(s,x.c)){for(const side of ['K','Q']){if(s.castle[x.c+side]&&((side==='K'&&!s.board[row][5]&&!s.board[row][6]&&!attacked(s,row,5,other(x.c)))||(side==='Q'&&!s.board[row][1]&&!s.board[row][2]&&!s.board[row][3]&&!attacked(s,row,3,other(x.c)))))add(row,side==='K'?6:2,{castle:side})}}}else{const dirs=x.p==='r'?[[1,0],[-1,0],[0,1],[0,-1]]:x.p==='b' ? [[1,1],[1,-1],[-1,1],[-1,-1]]:[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]];for(const [dr,dc] of dirs){let rr=r+dr,cc=c+dc;while(inside(rr,cc)){if(!add(rr,cc))break;rr+=dr;cc+=dc}}}return out}
function apply(s,m){const n=clone(s),x=n.board[m.fr][m.fc];n.board[m.fr][m.fc]=null;n.board[m.tr][m.tc]=x;if(m.ep)n.board[m.tr+(x.c==='w'?1:-1)][m.tc]=null;if(m.castle){const row=m.tr,from=m.castle==='K'?7:0,to=m.castle==='K'?5:3;n.board[row][to]=n.board[row][from];n.board[row][from]=null}if(x.p==='p'&&(m.tr===0||m.tr===7))x.p='q';n.enPassant=x.p==='p'&&Math.abs(m.tr-m.fr)===2?`${(m.tr+m.fr)/2},${m.fc}`:null;if(x.p==='k'){n.castle[x.c+'K']=n.castle[x.c+'Q']=false}if(x.p==='r'){if(m.fc===0)n.castle[x.c+'Q']=false;if(m.fc===7)n.castle[x.c+'K']=false}n.turn=other(s.turn);n.last=m;return n}
function movesFor(s,color=s.turn){const out=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(s.board[r][c]?.c===color)for(const m of pseudo(s,r,c)){const n=apply(s,m);if(!inCheck(n,color))out.push(m)}return out}
function notation(s,m){const x=s.board[m.fr][m.fc], capture=Boolean(s.board[m.tr][m.tc])||m.ep;return x.p==='p'?(capture?String.fromCharCode(97+m.fc)+'x':'')+String.fromCharCode(97+m.tc)+(8-m.tr):names[x.p][0].toUpperCase()+(capture?'x':'')+String.fromCharCode(97+m.tc)+(8-m.tr)}
function render(){boardEl.innerHTML='';const rows=state.playerColor==='b'?[7,6,5,4,3,2,1,0]:[0,1,2,3,4,5,6,7];const cols=state.playerColor==='b'?[7,6,5,4,3,2,1,0]:[0,1,2,3,4,5,6,7];const targets=new Set(legal.map(m=>`${m.tr},${m.tc}`));for(const r of rows)for(const c of cols){const b=document.createElement('button');b.className=`square ${(r+c)%2?'dark':'light'}`;if(selected&&selected[0]===r&&selected[1]===c)b.classList.add('selected');if(state.last&&(state.last.fr===r&&state.last.fc===c||state.last.tr===r&&state.last.tc===c))b.classList.add('last-move');if(targets.has(`${r},${c}`))b.classList.add(state.board[r][c]?'capture':'legal');const x=state.board[r][c];if((state.playerColor==='w'&&r===7)||(state.playerColor==='b'&&r===0)){const f=document.createElement('span');f.className='coord file';f.textContent=String.fromCharCode(97+c);b.append(f)}if((state.playerColor==='w'&&c===0)||(state.playerColor==='b'&&c===7)){const n=document.createElement('span');n.className='coord rank';n.textContent=8-r;b.append(n)}if(x){const sp=document.createElement('span');sp.className=`piece ${x.c==='w'?'white-piece':'black-piece'}`;sp.textContent=pieces[x.c][x.p];b.append(sp);b.setAttribute('aria-label',`${x.c==='w'?'White':'Black'} ${names[x.p]}`)}b.addEventListener('click',()=>clickSquare(r,c));boardEl.append(b)}}function clickSquare(r,c){if(thinking||state.over||state.turn!==state.playerColor)return;const x=state.board[r][c];const chosen=legal.find(m=>m.tr===r&&m.tc===c);if(chosen){if(!makeMove(chosen))return;selected=null;legal=[];render();if(!state.over){thinking=true;thinkingEl.classList.add('show');turnLabel.textContent='Nova is thinking…';setTimeout(botMove,350)}return}if(x?.c===state.playerColor){selected=[r,c];legal=movesFor(state,state.playerColor).filter(m=>m.fr===r&&m.fc===c)}else{selected=null;legal=[]}render()}function makeMove(m){const x=state.board[m.fr][m.fc];let promotion='q';if(x.p==='p'&&(m.tr===0||m.tr===7)&&state.turn===state.playerColor){const choice=(window.prompt('Promote to: Queen, Rook, Bishop, or Knight','Queen')||'').trim().toLowerCase();const opts={queen:'q',rook:'r',bishop:'b',knight:'n'};promotion=opts[choice];if(!promotion)return false}state.snapshots.push(JSON.stringify({board:state.board,turn:state.turn,castle:state.castle,enPassant:state.enPassant,last:state.last,moves:state.moves}));const note=notation(state,m);state=apply(state,m);if(x.p==='p'&&(m.tr===0||m.tr===7))state.board[m.tr][m.tc].p=promotion;state.moves.push(note);checkEnd();updateLog();return true}function checkEnd(){const ms=movesFor(state);if(!ms.length){state.over=true;const check=inCheck(state,state.turn);showToast(check?`${state.turn==='w'?'You':'Nova'} wins by checkmate.`:'Draw by stalemate.')}turnLabel.textContent=state.over?'Game over':state.turn==='w'?'Your turn':'Nova’s turn'}
function evaluate(s,bot){const val={p:100,n:320,b:330,r:500,q:900,k:20000};let score=0;for(let r=0;r<8;r++)for(let c=0;c<8;c++){const x=s.board[r][c];if(!x)continue;let v=val[x.p];if(x.p==='p')v+=Math.max(0,x.c==='w'?6-r:r-1)*6;if('nbq'.includes(x.p)&&r>=2&&r<=5&&c>=2&&c<=5)v+=18;if(x.p==='n'&&[[0,1],[0,6],[7,1],[7,6]].some(([a,b])=>a===r&&b===c))v-=18;score+=(x.c===bot?1:-1)*v}return score}
function botMove(){if(state.over){thinking=false;thinkingEl.classList.remove('show');return}const bot=state.playerColor==='w'?'b':'w';const ms=movesFor(state,bot),cfg=levels[difficulty];if(!ms.length){checkEnd();return}const deadline=performance.now()+cfg.time*1000;let scored=[];for(const m of ms){if(performance.now()>=deadline&&scored.length)break;scored.push([search(apply(state,m),cfg.depth-1,-Infinity,Infinity,bot==='w'?'b':'w',bot,deadline),m])}if(!scored.length)scored=[[0,ms[0]]];const best=Math.max(...scored.map(x=>x[0]));const pool=Math.random()<cfg.random?scored.sort((a,b)=>b[0]-a[0]).slice(0,3):scored.filter(x=>x[0]===best);makeMove(pool[Math.floor(Math.random()*pool.length)][1]);thinking=false;thinkingEl.classList.remove('show');render()}
function search(s,d,a,b,color,bot,deadline){if(performance.now()>=deadline||d<=0)return evaluate(s,bot);const ms=movesFor(s,color);if(!ms.length)return inCheck(s,color)?(color===bot?-99999:99999):0;ms.sort((x,y)=>(s.board[y.tr][y.tc]?1:0)-(s.board[x.tr][x.tc]?1:0));if(color===bot){let v=-Infinity;for(const m of ms){v=Math.max(v,search(apply(s,m),d-1,a,b,bot==='w'?'b':'w',bot,deadline));a=Math.max(a,v);if(a>=b)break}return v}let v=Infinity;for(const m of ms){v=Math.min(v,search(apply(s,m),d-1,a,b,bot==='w'?'b':'w',bot,deadline));b=Math.min(b,v);if(a>=b)break}return v}function updateLog(){moveCount.textContent=`${Math.ceil(state.moves.length/2)} / ${Math.ceil(state.moves.length/2)}`;if(!state.moves.length){moveList.innerHTML='<div class="empty-state"><span>♟</span><p>Your moves will appear here.</p></div>';return}moveList.innerHTML='';for(let i=0;i<state.moves.length;i+=2){const row=document.createElement('div');row.className='move-row';row.innerHTML=`<span>${i/2+1}.</span><span class="${i===state.moves.length-1?'current':''}">${state.moves[i]||''}</span><span class="${i+1===state.moves.length-1?'current':''}">${state.moves[i+1]||''}</span>`;moveList.append(row)}moveList.scrollTop=moveList.scrollHeight}
function showToast(msg){toast.textContent=msg;toast.classList.add('visible');setTimeout(()=>toast.classList.remove('visible'),3000)}
let selectedSide='w';
document.querySelectorAll('.difficulty').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.difficulty').forEach(x=>x.classList.remove('active'));b.classList.add('active');difficulty=b.dataset.level;botLevelLabel.textContent=levels[difficulty].label}));
document.querySelectorAll('.side-button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.side-button').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedSide=b.dataset.side}));
document.querySelector('#newGame').addEventListener('click',()=>{state=fresh(selectedSide);selected=null;legal=[];thinking=false;thinkingEl.classList.remove('show');turnLabel.textContent=state.turn===state.playerColor?'Your turn':'Nova is thinking…';updateLog();render();showToast('A fresh board is ready.');if(state.turn!==state.playerColor)setTimeout(()=>{thinking=true;thinkingEl.classList.add('show');botMove()},350)});
document.querySelector('#undoMove').addEventListener('click',undoMove);
function undoMove(){if(thinking||!state.snapshots.length)return;const steps=state.turn===state.playerColor&&state.snapshots.length>=2?2:1;for(let i=0;i<steps;i++){const old=JSON.parse(state.snapshots.pop());state.board=old.board;state.turn=old.turn;state.castle=old.castle;state.enPassant=old.enPassant;state.last=old.last;state.moves=old.moves}state.over=false;selected=null;legal=[];turnLabel.textContent=state.turn===state.playerColor?'Your turn':'Nova is thinking…';updateLog();render()}
document.querySelector('#themeToggle').addEventListener('click',()=>document.body.classList.toggle('dark'));
state=fresh('w');render();updateLog();